import { Router } from "express";
import { authMiddleware } from "../../middleware/auth";
import { adminMiddleware } from "../../middleware/admin";
import { requirePermission } from "../../middleware/rbac";
import { updateUserRoleVerification, decideVerification } from "./admin.controller";
import { getVerificationRequestById, getVerificationRequests } from "./verification.controller";
import { getPeople, getPersonById } from "./people.controller";
import { getBrandingController, updateBrandingController } from "./branding.controller";
import { getOperationalRides, getOperationalRideById, assignOperationalRideController, cancelOperationalRideController, interruptOperationalRideController, recoverOperationalRideController } from "./ride-operations.controller";
import { listEmergencyAdmin, getEmergencyAdmin, acknowledgeEmergencyAdminController, escalateEmergencyAdminController, resolveEmergencyAdminController, assignResponderAdmin, responderStatusAdmin } from "./emergency.controller";
import { getRidePricingController, updateRidePricingController } from "./pricing.controller";
import { listAdminPaymentsController, refundAdminPaymentController } from "./finance.controller";
import { listAdminPermissions, updateAdminPermissions } from "./rbac.controller";
import { getAdminAnalytics } from "./analytics.controller";
import { getFinanceSummary } from "./finance.controller";
import { listAdminNotifications, sendAdminNotification } from "./notification.controller";
import { listAdminPromotionsController, createAdminPromotionController, updateAdminPromotionController, deactivateAdminPromotionController } from "./promotion.controller";
import { listAdminSupportTicketsController, replyAdminSupportTicketController, updateAdminSupportTicketController } from "./support-admin.controller";

const router = Router();
const admin = [authMiddleware, adminMiddleware] as const;
router.get("/analytics", ...admin, requirePermission("analytics.read"), getAdminAnalytics);
router.get("/finance/summary", ...admin, requirePermission("payments.read"), getFinanceSummary);
router.get("/finance/payments", ...admin, requirePermission("payments.read"), listAdminPaymentsController);
router.post("/finance/payments/:id/refund", ...admin, requirePermission("payments.refund"), refundAdminPaymentController);
router.get("/notifications", ...admin, requirePermission("notifications.read"), listAdminNotifications);
router.post("/notifications", ...admin, requirePermission("notifications.manage"), sendAdminNotification);
router.get("/promotions", ...admin, requirePermission("promotions.read"), listAdminPromotionsController);
router.post("/promotions", ...admin, requirePermission("promotions.manage"), createAdminPromotionController);
router.patch("/promotions/:id", ...admin, requirePermission("promotions.manage"), updateAdminPromotionController);
router.post("/promotions/:id/deactivate", ...admin, requirePermission("promotions.manage"), deactivateAdminPromotionController);
router.get("/verification/requests", ...admin, requirePermission("drivers.verify", "guides.verify"), getVerificationRequests);
router.get("/verification/requests/:id", ...admin, requirePermission("drivers.verify", "guides.verify"), getVerificationRequestById);
router.get("/people", ...admin, requirePermission("users.read"), getPeople);
router.get("/people/:id", ...admin, requirePermission("users.read"), getPersonById);
router.patch("/users/:userId/roles/:role", ...admin, requirePermission("drivers.verify", "guides.verify"), updateUserRoleVerification);
router.patch("/verification/requests/:id", ...admin, requirePermission("drivers.verify", "guides.verify"), decideVerification);
router.get("/branding", ...admin, requirePermission("branding.read"), getBrandingController);
router.patch("/branding", ...admin, requirePermission("branding.manage"), updateBrandingController);
router.get("/pricing/ride", ...admin, requirePermission("pricing.read"), getRidePricingController);
router.patch("/pricing/ride", ...admin, requirePermission("pricing.manage"), updateRidePricingController);
router.get("/rides", ...admin, requirePermission("rides.read"), getOperationalRides);
router.get("/rides/:id", ...admin, requirePermission("rides.read"), getOperationalRideById);
router.post("/rides/:id/assign", ...admin, requirePermission("rides.manage"), assignOperationalRideController);
router.post("/rides/:id/cancel", ...admin, requirePermission("rides.manage"), cancelOperationalRideController);
router.post("/rides/:id/interrupt", ...admin, requirePermission("rides.manage"), interruptOperationalRideController);
router.post("/rides/:id/recover", ...admin, requirePermission("rides.manage"), recoverOperationalRideController);
router.get("/emergency/incidents", ...admin, requirePermission("emergency.read"), listEmergencyAdmin);
router.get("/emergency/incidents/:id", ...admin, requirePermission("emergency.read"), getEmergencyAdmin);
router.post("/emergency/incidents/:id/acknowledge", ...admin, requirePermission("emergency.manage"), acknowledgeEmergencyAdminController);
router.post("/emergency/incidents/:id/escalate", ...admin, requirePermission("emergency.manage"), escalateEmergencyAdminController);
router.post("/emergency/incidents/:id/resolve", ...admin, requirePermission("emergency.manage"), resolveEmergencyAdminController);
router.post("/emergency/incidents/:id/responders", ...admin, requirePermission("emergency.manage"), assignResponderAdmin);
router.patch("/emergency/responders/:assignmentId", ...admin, requirePermission("emergency.manage"), responderStatusAdmin);
router.get("/rbac/users/:userId/permissions", ...admin, requirePermission("admin.permissions.read"), listAdminPermissions);
router.put("/rbac/users/:userId/permissions", ...admin, requirePermission("admin.permissions.manage"), updateAdminPermissions);
export default router;

router.get("/support/tickets", ...admin, requirePermission("support.read"), listAdminSupportTicketsController);
router.post("/support/tickets/:id/reply", ...admin, requirePermission("support.manage"), replyAdminSupportTicketController);
router.patch("/support/tickets/:id/status", ...admin, requirePermission("support.manage"), updateAdminSupportTicketController);
