import { Request, Response } from "express";
import { acknowledgeEmergencyAdmin, assignEmergencyResponder, escalateEmergencyAdmin, getEmergencyIncidentAdmin, listEmergencyIncidents, resolveEmergencyAdmin, updateEmergencyResponder } from "./emergency.service";
function param(v:string|string[]|undefined){return Array.isArray(v)?v[0]:v}
function ok(req:Request,res:Response,data:unknown){return res.json({success:true,data,error:null,requestId:req.requestId})}
function fail(req:Request,res:Response,e:unknown){const m=e instanceof Error?e.message:"INTERNAL_SERVER_ERROR";const map:Record<string,[number,string]>={EMERGENCY_NOT_FOUND:[404,"Emergency incident not found"],INVALID_EMERGENCY_TRANSITION:[409,"Invalid emergency state transition"],RESPONDER_NOT_FOUND:[404,"Responder not found"],EMERGENCY_ALREADY_RESOLVED:[409,"Emergency is already resolved"],RESPONDER_ASSIGNMENT_NOT_FOUND:[404,"Responder assignment not found"],INVALID_RESPONDER_STATUS:[400,"Invalid responder status"]};const x=map[m]||[500,"Something went wrong"];return res.status(x[0]).json({success:false,data:null,error:{code:m,message:x[1]},requestId:req.requestId})}
export async function listEmergencyAdmin(req:Request,res:Response){try{return ok(req,res,await listEmergencyIncidents({state:typeof req.query.state==='string'?req.query.state:undefined,category:typeof req.query.category==='string'?req.query.category:undefined,limit:typeof req.query.limit==='string'?Number(req.query.limit):100}))}catch(e){return fail(req,res,e)}}
export async function getEmergencyAdmin(req:Request,res:Response){try{const id=param(req.params.id);if(!id)throw new Error("EMERGENCY_NOT_FOUND");return ok(req,res,await getEmergencyIncidentAdmin(id))}catch(e){return fail(req,res,e)}}
async function action(req:Request,res:Response,fn:(actor:string,id:string,requestId?:string)=>Promise<unknown>){try{const id=param(req.params.id);if(!id)throw new Error("EMERGENCY_NOT_FOUND");return ok(req,res,await fn(req.user!.id,id,req.requestId))}catch(e){return fail(req,res,e)}}
export const acknowledgeEmergencyAdminController=(req:Request,res:Response)=>action(req,res,acknowledgeEmergencyAdmin);
export const escalateEmergencyAdminController=(req:Request,res:Response)=>action(req,res,escalateEmergencyAdmin);
export const resolveEmergencyAdminController=(req:Request,res:Response)=>action(req,res,resolveEmergencyAdmin);
export async function assignResponderAdmin(req:Request,res:Response){try{const id=param(req.params.id);const responderId=typeof req.body?.responderId==='string'?req.body.responderId:undefined;if(!id||!responderId)throw new Error("RESPONDER_NOT_FOUND");return ok(req,res,await assignEmergencyResponder(req.user!.id,id,responderId,req.requestId))}catch(e){return fail(req,res,e)}}
export async function responderStatusAdmin(req:Request,res:Response){try{const id=param(req.params.assignmentId);const status=typeof req.body?.status==='string'?req.body.status:undefined;if(!id||!status)throw new Error("INVALID_RESPONDER_STATUS");return ok(req,res,await updateEmergencyResponder(req.user!.id,id,status,req.requestId))}catch(e){return fail(req,res,e)}}
