import { Request, Response } from "express";
import { getFinanceSummary } from "./finance.controller";
import { listAdminPayments, adminRefundPayment } from "./finance.service";

function int(v:unknown,d:number,max:number){const n=Number(v);return Number.isInteger(n)&&n>0?Math.min(n,max):d;}
function date(v:unknown){if(typeof v!=="string"||!v)return undefined;const d=new Date(v);return Number.isNaN(d.getTime())?undefined:d;}
function fail(res:Response,req:Request,e:unknown){const code=e instanceof Error?e.message:"INTERNAL_ERROR";const map:any={PAYMENT_NOT_FOUND:[404,"Payment not found"],REFUND_PROVIDER_UNSUPPORTED:[409,"Payment provider does not support admin refunds"],PAYMENT_NOT_REFUNDABLE:[409,"Payment is not refundable"],PAYMENT_PROVIDER_ID_MISSING:[409,"Provider payment id is missing"],REFUND_ALREADY_PROCESSING:[409,"A refund is already processing"],INVALID_REFUND_AMOUNT:[400,"Invalid refund amount"],RAZORPAY_NOT_CONFIGURED:[503,"Razorpay is not configured"],RAZORPAY_REFUND_FAILED:[502,"Razorpay refund failed"]};const [status,message]=map[code]??[500,"Internal server error"];return res.status(status).json({success:false,data:null,error:{code,message},requestId:req.requestId});}
export async function listAdminPaymentsController(req:Request,res:Response){const from=date(req.query.from),to=date(req.query.to);if(req.query.from&&!from||req.query.to&&!to)return res.status(400).json({success:false,error:{code:"INVALID_DATE_RANGE",message:"Invalid date range"},requestId:req.requestId});if(from&&to&&from>to)return res.status(400).json({success:false,error:{code:"INVALID_DATE_RANGE",message:"from must be before to"},requestId:req.requestId});try{const data=await listAdminPayments({page:int(req.query.page,1,100000),limit:int(req.query.limit,25,100),status:typeof req.query.status==="string"?req.query.status.toUpperCase():undefined,provider:typeof req.query.provider==="string"?req.query.provider.toUpperCase():undefined,search:typeof req.query.search==="string"?req.query.search.trim():undefined,from,to});return res.json({success:true,data,error:null,requestId:req.requestId});}catch(e){return fail(res,req,e);}}
export async function refundAdminPaymentController(req:Request,res:Response){const paymentId=String(req.params.id||"");const reason=typeof req.body?.reason==="string"?req.body.reason.trim():"";const amount=req.body?.amount===undefined?undefined:Number(req.body.amount);if(!paymentId||reason.length<2||reason.length>500||(amount!==undefined&&(!Number.isFinite(amount)||amount<=0)))return res.status(400).json({success:false,error:{code:"VALIDATION_ERROR",message:"Valid reason and optional positive amount are required"},requestId:req.requestId});try{const data=await adminRefundPayment(paymentId,req.user!.id,{amount,reason},req.requestId);return res.status(201).json({success:true,data,error:null,requestId:req.requestId});}catch(e){return fail(res,req,e);}}
