import type {Request,Response} from "express";
import {errorResponse,successResponse} from "../../core/api-response";
import {z} from "zod";
import {createAdminPromotion,deactivateAdminPromotion,listAdminPromotions,updateAdminPromotion} from "./promotion.service";
const createSchema=z.object({code:z.string().trim().min(2).max(50).transform(v=>v.toUpperCase()),title:z.string().trim().min(2).max(200),description:z.string().trim().max(1000).optional(),discountType:z.enum(["PERCENTAGE","FIXED"]),discountValue:z.number().positive(),maxDiscount:z.number().positive().optional(),minRideAmount:z.number().nonnegative().optional(),usageLimit:z.number().int().positive().optional(),startsAt:z.coerce.date(),expiresAt:z.coerce.date(),isActive:z.boolean().default(true)}).refine(v=>v.expiresAt>v.startsAt,{message:"expiresAt must be after startsAt"});
const updateSchema=createSchema.omit({code:true}).partial();
function fail(res:Response,req:Request,e:unknown){const code=e instanceof Error?e.message:"INTERNAL_ERROR";const status=code==="PROMOTION_NOT_FOUND"?404:code==="NO_UPDATE_FIELDS"?400:code.toLowerCase().includes("unique")?409:500;return errorResponse(res,req.requestId,status,code,"Promotion operation failed")}
export async function listAdminPromotionsController(req:Request,res:Response){try{const page=Math.max(Number(req.query.page)||1,1),limit=Math.min(Math.max(Number(req.query.limit)||20,1),100);const active=req.query.active===undefined?undefined:String(req.query.active)==="true";return successResponse(res,req.requestId,await listAdminPromotions({page,limit,search:String(req.query.search||""),active}))}catch(e){return fail(res,req,e)}}
export async function createAdminPromotionController(req:Request,res:Response){const p=createSchema.safeParse(req.body);if(!p.success)return errorResponse(res,req.requestId,400,"VALIDATION_ERROR","Invalid promotion",p.error.flatten());try{return successResponse(res,req.requestId,await createAdminPromotion(req.user!.id,p.data),201)}catch(e){return fail(res,req,e)}}
export async function updateAdminPromotionController(req:Request,res:Response){const id=z.string().uuid().safeParse(req.params.id),p=updateSchema.safeParse(req.body);if(!id.success||!p.success)return errorResponse(res,req.requestId,400,"VALIDATION_ERROR","Invalid promotion update");try{return successResponse(res,req.requestId,await updateAdminPromotion(req.user!.id,id.data,p.data))}catch(e){return fail(res,req,e)}}
export async function deactivateAdminPromotionController(req:Request,res:Response){const id=z.string().uuid().safeParse(req.params.id);if(!id.success)return errorResponse(res,req.requestId,400,"VALIDATION_ERROR","Invalid promotion id");try{return successResponse(res,req.requestId,await deactivateAdminPromotion(req.user!.id,id.data))}catch(e){return fail(res,req,e)}}