import { prisma } from "../../core/prisma";
import { notifyUser } from "../notification/notification.service";

const HEARTBEAT_TIMEOUT_MS = Number(process.env.RIDE_HEARTBEAT_TIMEOUT_MS ?? 90_000);
const DEVIATION_KM = Number(process.env.RIDE_ROUTE_DEVIATION_KM ?? 2);
const ALERT_COOLDOWN_MS = Number(process.env.RIDE_MONITOR_ALERT_COOLDOWN_MS ?? 300_000);

function distanceKm(aLat:number,aLng:number,bLat:number,bLng:number){const r=6371,dLat=(bLat-aLat)*Math.PI/180,dLng=(bLng-aLng)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x));}
async function recent(rideId:string,type:string){return prisma.rideEvent.findFirst({where:{rideId,type,createdAt:{gte:new Date(Date.now()-ALERT_COOLDOWN_MS)}}});}

export async function getDriverHeartbeat(rideId:string,driverId:string){const last=await prisma.rideLocation.findFirst({where:{rideId,driverId},orderBy:{recordedAt:"desc"},select:{recordedAt:true,latitude:true,longitude:true}});if(!last)return {alive:false,lastSeenAt:null};return {alive:Date.now()-last.recordedAt.getTime()<=HEARTBEAT_TIMEOUT_MS,lastSeenAt:last.recordedAt,latitude:last.latitude,longitude:last.longitude};}

export async function detectRouteDeviation(rideId:string){const ride=await prisma.ride.findUnique({where:{id:rideId},select:{id:true,riderId:true,pickupLatitude:true,pickupLongitude:true,dropoffLatitude:true,dropoffLongitude:true,status:true}});if(!ride||ride.status!=="IN_PROGRESS")return null;const last=await prisma.rideLocation.findFirst({where:{rideId},orderBy:{recordedAt:"desc"},select:{latitude:true,longitude:true,recordedAt:true,driverId:true}});if(!last)return null;const deviation=Math.min(distanceKm(last.latitude,last.longitude,ride.pickupLatitude,ride.pickupLongitude),distanceKm(last.latitude,last.longitude,ride.dropoffLatitude,ride.dropoffLongitude));if(deviation<DEVIATION_KM||await recent(rideId,"ROUTE_DEVIATION"))return null;const event=await prisma.rideEvent.create({data:{rideId,actorUserId:last.driverId,type:"ROUTE_DEVIATION",payload:{distanceFromKnownEndpointKm:deviation,recordedAt:last.recordedAt.toISOString()}}});void notifyUser(ride.riderId,"Route deviation detected","Your ride appears to be away from the expected route. Safety monitoring is active.",{rideId,status:ride.status,distanceKm:deviation}).catch(()=>undefined);return event;}

export async function monitorActiveRides(){const rides=await prisma.ride.findMany({where:{status:"IN_PROGRESS"},select:{id:true,riderId:true,assignments:{where:{status:"ACCEPTED"},select:{driverId:true},take:1}},take:100});const stale:string[]=[];for(const ride of rides){const d=ride.assignments[0];if(!d)continue;const hb=await getDriverHeartbeat(ride.id,d.driverId);if(!hb.alive){stale.push(ride.id);if(!(await recent(ride.id,"RIDE_HEARTBEAT_TIMEOUT"))){await prisma.rideEvent.create({data:{rideId:ride.id,actorUserId:d.driverId,type:"RIDE_HEARTBEAT_TIMEOUT",payload:{lastSeenAt:hb.lastSeenAt}}});void notifyUser(ride.riderId,"Driver connection lost","We have not received the driver's location recently. Safety monitoring has been alerted.",{rideId:ride.id,status:ride.status}).catch(()=>undefined);}}await detectRouteDeviation(ride.id);}return stale;}

export function startRideMonitor(){if(process.env.RIDE_MONITOR_ENABLED!=="true")return;const interval=Math.max(5000,Number(process.env.RIDE_MONITOR_INTERVAL_MS??30000));void monitorActiveRides();setInterval(()=>void monitorActiveRides(),interval);}
