import express from "express";
import dotenv from "dotenv";
import { requestIdMiddleware } from "./middleware/request-id";
import authRouter from "./modules/auth/auth.route";
import usersRouter from "./modules/users/users.route";
import adminRouter from "./modules/admin/admin.route";
import verificationRouter from "./modules/verification/verification.route";
import providerRouter from "./modules/provider/provider.route";
import rideRouter from "./modules/ride/ride.route";
import paymentRouter from "./modules/payment/payment.route";
import notificationRouter from "./modules/notification/notification.route";
import safetyRouter from "./modules/safety/safety.route";
import savedPlaceRouter from "./modules/saved-place/saved-place.route";
import ratingRouter from "./modules/rating/rating.route";
import supportRouter from "./modules/support/support.route";
import { errorHandler } from "./middleware/error-handler";

dotenv.config();
const app = express();
app.use(express.json());
app.use(requestIdMiddleware);
app.get("/health", (_req, res) => res.status(200).json({ success: true, data: { status: "ok" }, error: null, requestId: _req.requestId }));
app.use("/api/v1/auth", authRouter);
app.use("/api/v1/users", usersRouter);
app.use("/api/v1/admin", adminRouter);
app.use("/api/v1/verification", verificationRouter);
app.use("/api/v1/providers", providerRouter);
app.use("/api/v1/rides", rideRouter);
app.use("/api/v1/payments", paymentRouter);
app.use("/api/v1/notifications", notificationRouter);
app.use("/api/v1", safetyRouter);
app.use("/api/v1/places/saved", savedPlaceRouter);
app.use("/api/v1", ratingRouter);
app.use("/api/v1/support/tickets", supportRouter);
app.use(errorHandler);
export default app;
